// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("calendar.caldav.googleResync", 1679479554);
user_pref("calendar.list.sortOrder", "2e1f6aa4-c31f-483b-95ee-b1a36e30c6d2");
user_pref("calendar.registry.2e1f6aa4-c31f-483b-95ee-b1a36e30c6d2.calendar-main-default", true);
user_pref("calendar.registry.2e1f6aa4-c31f-483b-95ee-b1a36e30c6d2.calendar-main-in-composite", true);
user_pref("calendar.registry.2e1f6aa4-c31f-483b-95ee-b1a36e30c6d2.disabled", true);
user_pref("calendar.registry.2e1f6aa4-c31f-483b-95ee-b1a36e30c6d2.name", "Privat");
user_pref("calendar.registry.2e1f6aa4-c31f-483b-95ee-b1a36e30c6d2.type", "storage");
user_pref("calendar.registry.2e1f6aa4-c31f-483b-95ee-b1a36e30c6d2.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Berlin");
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1679479553);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230131132728");
user_pref("extensions.lastAppVersion", "102.7.1");
user_pref("extensions.lastPlatformVersion", "102.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"3cf30503-f315-4dec-9ed4-04f56dbae614\",\"google@search.mozilla.org\":\"01f9c6a4-46ba-4a42-86a4-11690edf19ec\",\"ddg@search.mozilla.org\":\"46150d8c-4c3a-4fa0-afef-f1cdc7ab35f5\",\"amazondotcom@search.mozilla.org\":\"92978cb7-e4e7-497d-8eb9-bf8aee7bec97\",\"amazon@search.mozilla.org\":\"4b394bc3-72b5-457a-aebc-3396ac369c0f\",\"leo_ende_de@search.mozilla.org\":\"0728dd04-d082-4eef-a719-86df60faf048\",\"wikipedia@search.mozilla.org\":\"bb3f5e09-62a1-468b-b962-541b7a7f937a\",\"bing@search.mozilla.org\":\"db418359-5c07-4630-b862-d89642f4a5df\",\"ecosia@search.mozilla.org\":\"2a6bd4e2-e500-467d-bbab-5220f5dcbc10\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 34);
user_pref("mailnews.database.global.datastore.id", "ab7001f0-bfe4-477b-bf6e-1aa9aade5d8");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "102.7.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Wichtig");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Dienstlich");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Persönlich");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "Zu erledigen");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Später");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.cachedClientID", "f5f0d700-94fb-458f-87dd-17ace90d6d4c");
user_pref("toolkit.telemetry.previousBuildID", "20230131132728");
